# Generated by Django 2.1.5 on 2019-05-23 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hometutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevents',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='upcomingevents',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
