# Generated by Django 2.1.5 on 2019-02-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometutorial', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
