# Generated by Django 2.1.5 on 2019-02-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometutorial', '0003_delete_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
