# Generated by Django 2.1.5 on 2019-03-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometutorial', '0005_login_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='session_key',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
