# Generated by Django 2.1.5 on 2019-02-14 12:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythontutorial', '0003_videouploader_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='videoupload',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
