# Generated by Django 2.1.5 on 2019-02-14 13:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythontutorial', '0005_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
